[package]
name = "kalavar-core"
version = "0.1.0"
authors = ["fatalcenturion <tom.b.2k2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-bincode = "0.1.0"
tokio = { version = "1.0.0", features = ["full"] }
chrono = "0.4.19"