name: Build Docs
on:
  push:
    branches: [main]
    tags-ignore: [dev]
    paths:
      - 'src/*'
    paths-ignore:
      - 'docs/*'
defaults:
  run:
    shell: bash

jobs:
  doc_api:
    name: Document Crate
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dbroken_intra_doc_links
      OPENVINO_SKIP_LINKING: 1
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: main
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses: actions-rs/cargo@v1
      with: 
        command: doc
        args: --no-deps --document-private-items 
    - name: Commit documentation
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Built docs for ${{github.sha}}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
