name: Build Docs
on:
  push:
    branches: [main]
    tags-ignore: [dev]
    paths-ignore: ['docs/*', '.github/*']
defaults:
  run:
    shell: bash

jobs:
  doc_api:
    name: Document Crate
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Z unstable-options --static-root-path "https://dev.kalavar.cf/static/"
      OPENVINO_SKIP_LINKING: 1
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: main
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
    - name: compute-sha
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Move Old Content
      run: |
        mkdir -p ./docs/${{ steps.vars.outputs.sha_short }}
        mkdir -p ./docs/static
        mkdir -p ./docs/latest
        cp -r ./docs/latest ./docs/${{ steps.vars.outputs.sha_short }}
        rm -r ./docs/latest
    - name: Rustdoc
      run: |
        cargo rustdoc --target-dir './docs/latest'
    - name: Commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Built docs for ${{ steps.vars.outputs.sha_short }}" -a
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
