name: Build Docs
on:
  push:
    branches: [main]
    tags-ignore: [dev]
  pull_request:
    branches: [main]
defaults:
  run:
    shell: bash

jobs:
  doc_api:
    name: Document Crate
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dbroken_intra_doc_links
      OPENVINO_SKIP_LINKING: 1
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: main
        submodules: true
    - uses: ./.github/actions/install-rust
      with:
        toolchain: nightly
    - run: cargo doc --no-deps --document-private-items
    - uses: actions/upload-artifact@v1
      with:
        name: doc-api
        path: doc
