name: Build Docs
on:
  push:
    branches: [main]
defaults:
  run:
    shell: bash

jobs:
  doc_api:
    if: |
      !contains(github.event.head_commit.message, 'Built docs for') && contains(github.event.head_commit.message, '[doc]')
    name: Document Crate
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Z unstable-options --static-root-path /static/
      OPENVINO_SKIP_LINKING: 1
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: main
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
#     - name: compute-sha
#       id: vars
#       run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#     - name: Remove Old Content
#       run: |
#         rm -r ./docs/latest
#         mkdir -p ./docs/${{ steps.vars.outputs.sha_short }}
#         mkdir -p ./docs/static
    - name: Rustdoc
      run: |
        cargo rustdoc --target-dir './docs/latest'
    - name: Commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Built docs for ${{ steps.vars.outputs.sha_short }}" -a
        git pull --rebase
#        cp -r ./docs/latest/doc/* ./docs/${{ steps.vars.outputs.sha_short }}
#        rm -r ./docs/latest
#        mkdir -p ./docs/latest
#        cp -r ./docs/${{ steps.vars.outputs.sha_short }}/* ./docs/latest/
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
