name: Build Docs
on:
  push:
    branches: [main, dev]
defaults:
  run:
    shell: bash

jobs:
  doc_api:
    if: |
      !contains(github.event.head_commit.message, 'Built docs for') && contains(github.event.head_commit.message, '[doc]')
    name: Document Crate
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Z unstable-options --static-root-path /static/
      OPENVINO_SKIP_LINKING: 1
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: main
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
#     - name: compute-sha
#       id: vars
#       run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
#     - name: Remove Old Content
#       run: |
#         rm -r ./docs/latest
#         mkdir -p ./docs/${{ steps.vars.outputs.sha_short }}
    - uses: nelonoel/branch-name@v1.0.1
    - run: echo ${BRANCH_NAME}
    - name: Rustdoc
      run: |
        cargo rustdoc --target-dir './docs/${BRANCH_NAME}/latest'
    - name: Push docs to site
      uses: cpina/github-action-push-to-another-repository@cp_instead_of_deleting
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        target-branch: 'main' 
        source-directory: './docs/${BRANCH_NAME}/latest'
        destination-github-username: 'KalavarDB'
        destination-repository-name: 'dev.kalavar.cf'
        user-email: 'tom.b.2k2@gmail.com'
        commit-message: 'See ORIGIN_COMMIT'
