# This is a basic workflow to help you get started with Actions

name: TODO -> Issue

on: 
  push:
    branches: ["master"]
  workflow_dispatch:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v2.4.1"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
